// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQqJKJE3UU9f6wSa-G7-8CKEgewZyLsTs',
    appId: '1:633437805839:web:ab12c4b6d6c75fa54a727a',
    messagingSenderId: '633437805839',
    projectId: 'authentucate-3ba7a',
    authDomain: 'authentucate-3ba7a.firebaseapp.com',
    storageBucket: 'authentucate-3ba7a.firebasestorage.app',
    measurementId: 'G-T5N7ZEEMNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPJZqe8vmN-h9RqEiidoJptgSlfqsi198',
    appId: '1:633437805839:android:d5ac73738fe9bf014a727a',
    messagingSenderId: '633437805839',
    projectId: 'authentucate-3ba7a',
    storageBucket: 'authentucate-3ba7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIe0TNjwNuCwH3cZc3zKXiqL_hCZS8QtE',
    appId: '1:633437805839:ios:051e1a412e9a86614a727a',
    messagingSenderId: '633437805839',
    projectId: 'authentucate-3ba7a',
    storageBucket: 'authentucate-3ba7a.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

}